with-expecter: true
packages:
  github.com/kimjooyoon/project_board_backend_go/internal/infrastructure/out/maria/article/query:
    config:
      all: True
      recursive: True
      filename: "mock_{{.InterfaceName}}.go"
      dir: "internal/mocks/infrastructure/article/out/mariadb/query"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks_{{.PackageName}}"
