with-expecter: true
packages:
  github.com/kimjooyoon/project_board_backend_go/pkg/app/article/repo:
    config:
      all: True
      recursive: True
      filename: "mock_{{.InterfaceName}}.go"
      dir: "mocks/{{.PackagePath}}"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks_{{.PackageName}}"
