with-expecter: true
packages:
  github.com/kimjooyoon/project_board_backend_go/internal/app/article/repo:
    config:
      all: True
      recursive: True
      filename: "mock_{{.InterfaceName}}.go"
      dir: "internal/mocks/app/article/repo"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks_{{.PackageName}}"
